name: .NET CI

on:
  push:
    branches: [ "main", "development" ]   # corre quando há push em main ou development
  pull_request:
    branches: [ "main", "development" ]   # corre em PRs para main ou development

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # ajusta conforme tua versão

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar solução
        run: dotnet build --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test --no-build --configuration Release --verbosity normal
